### ISSUE TITLE
Console error at startup with hot-reload

### ISSUE THREAD

**Issue by pjeby** [NomarCub/obsidian-open-vscode#10]
The error below appears in the dev console at startup if you have the hot-reload plugin enabled, but it hasn't loaded yet.  (There should be a `?` after `app.plugins.plugins["hot-reload"]`, before the `.enabledPlugins`.)

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'enabledPlugins') at OpenVSCode.onload (plugin:open-vscode:146:103)
```

**Comment by NomarCub** [comment]
I just published 1.2.2 with a fix for this. Let me know if there are any more problems.
