### ISSUE TITLE
Please add variable for current folder

### ISSUE THREAD

**Issue by gowerc** [NomarCub/obsidian-open-vscode#8]
Hi,

Would it be possible to add in a variable for the folder of the currently opened file?  A common use case I have that I have a file open in a directory and actually I want to open that whole directory (not the whole vault) in VScode.  I think this could easily be done by splitting out `{{filepath}}` into `{{path}}/{{file}}` (if possible)

**Comment by NomarCub** [comment]
Hi!
I don't want to change existing variables, that would affect existing users. I made a new, relative `{{folderpath}}` variable, locally. Would you test if this is adequate for you? Here's the new build: [main.zip](https://github.com/NomarCub/obsidian-open-vscode/files/10819060/main.zip).

**Comment by NomarCub** [comment]
If there's no demand, I'll close it for now. What extension did you go with?
