### ISSUE TITLE
Wrong community plugin url in README

### ISSUE THREAD

**Issue by misabiko** [NomarCub/obsidian-open-vscode#9]
I just found this plugin and got a bit confused since the "Here's the plugin in Obsidian's Community Plugins website" link in the README points to:
https://obsidian.md/plugins?id=copy-url-in-preview
when I suppose it should point to:
https://obsidian.md/plugins?id=open-vscode

Otherwise, the plugin's sidebar button worked wonders :)

**Comment by NomarCub** [comment]
Thanks! 🙌
